    __CONFIG    _CONFIG1, _LVP_OFF & _FCMEN_ON & _IESO_OFF & _BOR_OFF & _CPD_OFF & _CP_OFF & _MCLRE_ON & _PWRTE_ON & _WDT_OFF & _INTRC_OSC_NOCLKOUT
    __CONFIG    _CONFIG2, _WRT_OFF & _BOR21V
    LIST P=16F887
    INCLUDE <P16F887.INC>
    ORG 0
    
COLUM	EQU 0X20
ROW	EQU 0X21
CEROP	EQU 0X22
CONTC	EQU 0X23
CONTMOS	EQU 0X24
JUSTC	EQU 0X25
CONT	EQU 0X26
CONT2	EQU 0X27
CONT3	EQU 0X28
    
INICIO 
	    
	BSF	STATUS,RP0
	;BCF	STATUS,RP1
	MOVLW	B'00001111'
	BCF	OPTION_REG,NOT_RBPU
	MOVWF   TRISB
	CLRF	TRISA
	CLRF	TRISD
	CLRF	TRISC
	BCF	STATUS,RP0
	;BCF   STATUS,RP1
	
Programa
	
	MOVLW	B'11110101'
	MOVWF	PORTA
	
	GOTO Programa
	
	END
	



