    __CONFIG _CP_OFF & _WDT_OFF & _PWRTE_ON & _XT_OSC
    LIST P=16F84A
    INCLUDE <P16F84A.INC>
    ORG 0
    
CONT    EQU	0X0F
CONT2   EQU	0X11
CONT3   EQU	0X12
   
INICIO
    BSF	    STATUS,RP0
    ;CLRF    TRISA
    CLRF    TRISB
    BCF	    STATUS,RP0
    
PROGRAMA
    ;MOVLW	B'11110'
    ;MOVWF	PORTA
    MOVLW	B'11111111'
    MOVWF	PORTB
    CALL	TIME
    MOVLW	B'00000000'
    MOVWF	PORTB
    CALL	TIME
    GOTO	PROGRAMA
    
TIME
	MOVLW	D'30';TENEMOS UNA RUTINA DE TIEMPO DE APROXIMADAMENTE DE UN SEGUNDO
	MOVWF	CONT
TA
	MOVLW	D'100'
	MOVWF	CONT2
TB	
	MOVLW	D'100'
	MOVWF	CONT3
TC
	DECFSZ	CONT3
	GOTO	TC
	DECFSZ	CONT2
	GOTO	TB
	DECFSZ	CONT
	GOTO	TA
	RETURN
    END