    __CONFIG _CP_OFF & _WDT_OFF & _PWRTE_ON & _XT_OSC
    LIST P=16F84A
    INCLUDE <P16F84A.INC>
    ORG 0
    
CONT    EQU	0X0F
CONT2   EQU	0X11
CONT3   EQU	0X12
REGA    EQU	0X0C
REGB    EQU	0X0D
REGCOM  EQU	0X0E
REGSA	EQU	0X13
    
INICIO 
	    
	BSF	STATUS,RP0
	CLRF    TRISA
	CLRF    TRISB
	BCF	STATUS,RP0
		    
PRIN
	
	MOVLW	B'11110'
	MOVWF	PORTA
	MOVLW	B'00000001'
	MOVWF	REGA
	MOVLW	B'10000000'
	MOVWF	REGB
	MOVLW	B'00000001'
	MOVWF	REGCOM
	MOVLW	B'11110'
	MOVWF	REGSA

	
CODIGUIN
	CALL	FOOLISH;TENOMOS QUE ALTERNAR EL JUEGO DE LEDS POR LO MENOS 60 VECES EN UN SEGUNDO
	CALL	MOVA;MOVEMOS DOS VECES A POR CADA VEZ QUE MOVEMOS B
	CALL	FOOLISH
	CALL	MOVB
	CALL	FOOLISH
	CALL	MOVA
	GOTO	CODIGUIN
	
TIME
	MOVLW	D'250';250TENEMOS UNA RUTINA DE TIEMPO DE APROXIMADAMENTE 2/60 DE SEGUNDO
	MOVWF	CONT
TA
	MOVLW	D'10';10
	MOVWF	CONT2
TB	
	DECFSZ	CONT2
	GOTO	TB
	DECFSZ	CONT
	GOTO	TA
	RETURN
    
MOVA 
	BTFSC	REGA,7; DE JUEGO DE LED
	CALL	MOVJLEDA
	BTFSC	REGA,7
	GOTO	RESA
	RLF	REGA,1;EL MOVA NOS SIRVE PARA MOVER A Y SI EL REGISTRO YA ALCANZO SU POSICION FINAL CAMBIAMOS
	GOTO	RMA
RESA
	MOVLW	B'00000001'
	MOVWF	REGA
RMA
	RETURN
	
MOVB
	BTFSC	REGB,7; DE JUEGO DE LED
	GOTO	RESB
	RLF	REGB,1;MOVEMOS EL REGISTRO B
	GOTO	RMB
RESB
	MOVLW	B'00000001'
	MOVWF	REGB
RMB
	RETURN

PRA
	MOVF    REGA,0;MOSTRAMOS EL REGISTRO A
	MOVWF   PORTB
	RETURN

PRB
	MOVF    REGB,0;MOSTRAMOS EL REGISTRO B
	MOVWF   PORTB
	RETURN
	
MOVJLEDA
	
	BTFSC	REGCOM,0;EN EL REGISTRO COMPLEMENTARIO SOLO SE NECESITA DOS POSICIONES
	GOTO	ALGO2
	MOVLW	B'00000001'
	MOVWF	REGCOM
	MOVLW	B'11110'
	MOVWF	REGSA
	GOTO	RE
	
ALGO2
	MOVLW	B'00000010'
	MOVWF	REGCOM
	MOVLW	B'11101'
	MOVWF	REGSA
RE
	RETURN
	
SHOWLEDB
	MOVLW	B'11011';ENCENDEMOS LOS LED B
	MOVWF	PORTA
	RETURN

SHOWLEDA
	MOVF	REGSA,0;ENCENDEMOS LOS LED B
	MOVWF	PORTA
	RETURN

	
FOOLISH
	MOVLW	D'10';LA RUTINA TONTO ENGAÑA LOS OJOS PUES ENCIENDE Y APAGA LOS
	MOVWF	CONT3;LED DE A Y B APROXIMADAMENTE 1/6 VECES EN UN SEGUNDO

LEDITSHINE
	CALL	SHOWLEDA
	CALL	PRA
	CALL	TIME
	CALL	SHOWLEDB
	CALL	PRB
	CALL	TIME
	DECFSZ	CONT3
	GOTO	LEDITSHINE
	RETURN
	
    END