    __CONFIG _CP_OFF & _WDT_OFF & _PWRTE_ON & _XT_OSC
    LIST P=16F84A
    INCLUDE <P16F84A.INC>
    ORG 0
    
CONT    EQU	0X0F
CONT2   EQU	0X10
REG     EQU	0X0C
   
INICIO 
	    
	BSF	STATUS,RP0
	CLRF    TRISB
	MOVLW	B'00000001'
	MOVWF   TRISA
	BCF	STATUS,RP0
	
	CLRF	REG
		    
PRIN	
	MOVF	REG,W
	MOVWF	PORTB
PR
	BTFSS	PORTA,0	;SI ESTA EN O SE VUELVE A COMPARAR PORQUE NO HA HABIDO CAMBIO
	GOTO	PR	;SI ESTA EN 1 LLAMA AL TIEMPO Y CUANDO ESTE TERMINE INC
	CALL	TIME
	INCF	REG,1
	
PR2
	BTFSC	PORTA,0	;SI ESTA EN 1 SE VUELVE A COMPARAR PORQUE NO HA HABIDO CAMBIO
	GOTO	PR2	;SI ESTA EN 0 LLAMA AL TIEMPO Y CUANDO ESTE TERMINE EL PROGRAMA PUEDE CONTINUAR
	CALL	TIME
	
	
	GOTO	PRIN
	
TIME
	MOVLW	D'100'
	MOVWF	CONT
TB	
	MOVLW	D'100'
	MOVWF	CONT2
TC
	DECFSZ	CONT2
	GOTO	TC
	DECFSZ	CONT
	GOTO	TB
	RETURN
	
    END





