    __CONFIG _CP_OFF & _WDT_OFF & _PWRTE_ON & _XT_OSC
    LIST P=16F84A
    INCLUDE <P16F84A.INC>
    ORG 0
    
CONT    EQU	0X0F
CONT2   EQU	0X10
REGA    EQU	0X0C
REGB	EQU	0X0D
   
INICIO 
	    
	BSF	STATUS,RP0
	MOVLW	B'11111111'
	MOVWF   TRISB
	MOVLW	B'00000001'
	MOVWF   TRISA
	BCF	STATUS,RP0
	
	CLRF	REGA
	CLRF	REGB
		    
PRIN	
	
PR
	BTFSS	PORTA,0	;SI ESTA EN O SE VUELVE A COMPARAR PORQUE NO HA HABIDO CAMBIO
	GOTO	PR	;SI ESTA EN 1 LLAMA AL TIEMPO Y CUANDO ESTE TERMINE INC
	CALL	EliminadorRebotes
	MOVF	PORTB,W
	MOVWF	REGA
PR2
	BTFSC	PORTA,0	;SI ESTA EN 1 SE VUELVE A COMPARAR PORQUE NO HA HABIDO CAMBIO
	GOTO	PR2	;SI ESTA EN 0 LLAMA AL TIEMPO Y CUANDO ESTE TERMINE EL PROGRAMA PUEDE CONTINUAR
	CALL	EliminadorRebotes	
PRB
	BTFSS	PORTA,0	;SI ESTA EN O SE VUELVE A COMPARAR PORQUE NO HA HABIDO CAMBIO
	GOTO	PRB	;SI ESTA EN 1 LLAMA AL TIEMPO Y CUANDO ESTE TERMINE INC
	CALL	EliminadorRebotes
	MOVF	PORTB,W
	MOVWF	REGB
PRB2
	BTFSC	PORTA,0	;SI ESTA EN 1 SE VUELVE A COMPARAR PORQUE NO HA HABIDO CAMBIO
	GOTO	PRB2	;SI ESTA EN 0 LLAMA AL TIEMPO Y CUANDO ESTE TERMINE EL PROGRAMA PUEDE CONTINUAR
	CALL	EliminadorRebotes
	
COMPARACIONES
	
	MOVF	REGA,0
	SUBWF	REGB,0
	BTFSC	STATUS,Z
	GOTO	IGUAL
	BTFSC	STATUS,C
	GOTO	MAYOR
	GOTO	MENOR
	
REGRESO
	
	GOTO	PRIN
	
IGUAL
	MOVLW	B'00010'
	MOVWF	PORTA
	GOTO	REGRESO
	
MAYOR
	MOVLW	B'00100'
	MOVWF	PORTA
	GOTO	REGRESO

MENOR
	MOVLW	B'01000'
	MOVWF	PORTA
	GOTO	REGRESO
	
EliminadorRebotes
	MOVLW	D'100'
	MOVWF	CONT
TB	
	MOVLW	D'100'
	MOVWF	CONT2
TC
	DECFSZ	CONT2
	GOTO	TC
	DECFSZ	CONT
	GOTO	TB
	RETURN
	
    END








